[global_config]
  title_hide_sizetext = True
  title_transmit_bg_color = "#1e1e2e"
  title_transmit_fg_color = "#cdd6f4"
  title_receive_bg_color = "#313244"
  title_receive_fg_color = "#cdd6f4"
  title_inactive_bg_color = "#181825"
  title_inactive_fg_color = "#6c7086"
  inactive_color_offset = 0.8
  suppress_multiple_term_dialog = True
  title_use_system_font = False
  title_font = Hack Nerd Font 11

[keybindings]

[profiles]
  [[default]]
    cursor_color = "#f5e0dc"
    cursor_color_fg = False
    foreground_color = "#cdd6f4"
    background_color = "#1e1e2e"
    show_titlebar = False
    scrollbar_position = hidden
    scrollback_lines = 10000
    palette = "#45475a:#f38ba8:#a6e3a1:#f9e2af:#89b4fa:#f5c2e7:#94e2d5:#bac2de:#585b70:#f38ba8:#a6e3a1:#f9e2af:#89b4fa:#f5c2e7:#94e2d5:#a6adc8"
    use_system_font = False
    font = Hack Nerd Font 16
    use_custom_command = True
    custom_command = /bin/zsh
    copy_on_selection = True

[layouts]
  [[default]]
    [[[window0]]]
      type = Window
      size = 1200, 700
    [[[child1]]]
      type = Terminal
      parent = window0
      profile = default

[plugins]